
name: test-delopy

on:
  push:
    branches:
      - test


jobs:
   build:
     runs-on: ubuntu-latest
   
     steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
            node-version: '10.x'
            
      - name: install hexo
        run: npm install -g hexo-cli

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: hexo clean && hexo generate
        run: hexo clean && hexo generate

    


